resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: http://github.com/pivotalservices/pcf-pipelines.git
    branch: master

- name: pivnet-opsman-product
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: 1\.10\..*

- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}}

jobs:
- name: pave-iaas
  plan:
  - get: pcf-pipelines
  - task: pave
    file: pcf-pipelines/install-pcf/openstack/tasks/pave-openstack/task.yml
    params:
      EXTERNAL_NETWORK: {{external_network}}
      INFRA_NETWORK: {{infra_network}}
      INFRA_SUBNET: {{infra_subnet}}
      ERT_NETWORK: {{ert_network}}
      ERT_SUBNET: {{ert_subnet}}
      SERVICES_NETWORK: {{services_network}}
      SERVICES_SUBNET: {{services_subnet}}
      SERVICESOD_NETWORK: {{servicesod_network}}
      SERVICESOD_SUBNET: {{servicesod_subnet}}
      ADMIN_ROUTER: {{admin_router}}
      BACKEND_ROUTER: {{backend_router}}
      SECGROUP_NAME: {{secgroup_name}}
      OPENSTACK_CA_CERT: {{pre_os_cacert}}
      OS_PROJECT_ID: {{os_project_id}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_PROJECT_NAME: {{os_project_name}}
      OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_USERNAME: {{os_username}}
      OS_INTERFACE: {{os_interface}}

- name: deploy-opsman
  plan:
  - aggregate:
    - get: pivnet-opsman-product
      params:
        globs:
        - "*.raw"
    - get: pcf-pipelines
  - task: upload
    file: pcf-pipelines/install-pcf/openstack/tasks/upload-product-and-stemcell/task.yml
    params:
      OPENSTACK_CA_CERT: {{pre_os_cacert}}
      OPS_MGR_IMG_NAME: {{ops_mgr_img_name}}
      OS_PROJECT_ID: {{os_project_id}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_PROJECT_NAME: {{os_project_name}}
      OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_USERNAME: {{os_username}}
      OS_INTERFACE: {{os_interface}}
  - task: deploy
    file: pcf-pipelines/install-pcf/openstack/tasks/boot-opsman/task.yml
    params:
      EXTERNAL_NETWORK: {{external_network}}
      INFRA_NETWORK: {{infra_network}}
      OPENSTACK_CA_CERT: {{pre_os_cacert}}
      OS_PROJECT_ID: {{os_project_id}}
      OS_REGION_NAME: {{os_region_name}}
      OS_USER_DOMAIN_NAME: {{os_user_domain_name}}
      OS_PROJECT_NAME: {{os_project_name}}
      OS_IDENTITY_API_VERSION: {{os_identity_api_version}}
      OS_PASSWORD: {{os_password}}
      OS_AUTH_URL: {{os_auth_url}}
      OS_USERNAME: {{os_username}}
      OS_INTERFACE: {{os_interface}}
      OPS_MGR_IMG_NAME: {{ops_mgr_img_name}}
      OPS_MGR_SEC_GRP: {{ops_mgr_sec_grp}}
      OPS_MGR_KEY_NAME: {{ops_mgr_key_name}}
      OPS_MGR_FLV_NAME: {{ops_mgr_flv_name}}
      OPS_MGR_SRV_NAME: {{ops_mgr_srv_name}}

- name: configure-opsman
  plan:
  - aggregate:
    - get: tool-om
    - get: pcf-pipelines
  - task: configure-auth
    file: pcf-pipelines/tasks/config-opsman/task.yml
    params:
      OPS_MGR_HOST: {{opsman_uri}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}
